import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import "./defaults.css";
import { cn } from "@/lib/utils";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={cn(nunito.className, 'h-screen')}>{children}</body>
        </html>
    );
};