// must be in this order, defaults overrides globals
import "./globals.css";
import "./defaults.css";

import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { Providers } from "./providers";
import { Toaster } from "sonner";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <Providers>
            <html lang="en">
                <body className={cn(nunito.className, 'h-screen')}>
                    <Toaster richColors />
                    {children}
                </body>
            </html>
        </Providers>
    );
};